swagger:
  enable: true
  title: AA Life
  description: AA Life API Document
  version: 1.0
  url:
  author:
    name: Brother Lu
    email: 1285823170@qq.com
    url:

server:
  port: 80
  ssl:
    key-store: 1529882054683.pfx
    key-store-password:
