swagger:
  enable: true
  title: AA Life
  description: AA Life API Document
  version: 1.0
  url:
  author:
    name: Brother Lu
    email: 1285823170@qq.com
    url:

server:
  port: 443
  ssl:
    key-store: classpath:1529882054683.pfx
    key-store-password: 1529882054683
    keyAlisa: tomcat
    keyStoreType: PKCS12

spring:
  application: aalife
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/life_v2?zeroDateTimeBehavior=convertToNull&verifyServerCertificate=false&useSSL=true&useUnicode=true&characterEncoding=utf-8
    username: root
    password: mysql
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect